
* --------------------------------------------------------------------.
* This command file was generated by paneldata.org                    .
* --------------------------------------------------------------------.
* !!! I M P O R T A N T - W A R N I N G !!!                           .
* You alone are responsible for contents and appropriate.             .
* usage by accepting the usage agreement.                             .
* --------------------------------------------------------------------.
* Please report any errors of the code generated here                 .
* to soepmail@diw.de                                                  .
* --------------------------------------------------------------------.



* * * LOCAL VARIABLES * * *

global MY_PATH_IN   "D:\Labor_Econ_Term_Paper\SOEP\raw_data\SOEP-CORE.v37international_STATA\Stata\raw\"
global MY_PATH_OUT  "D:\Labor_Econ_Term_Paper\SOEP\work_data_2\"
global MY_FILE_OUT  ${MY_PATH_OUT}6.8.dta
global MY_LOG_FILE  ${MY_PATH_OUT}new.log
capture log close
log using "${MY_LOG_FILE}", text replace
set more off
set varabbrev off


** * * NOT PROCESSED * * *.



* * * PFAD * * *

use gebjahr bfnetto hid_2016 bdnetto cid hid_2012 bepop bfpop bapop bgpop bcnetto hid_2010 hid_2014 bbnetto banetto pid hid_2015 sex hid_2011 benetto bbpop bcpop bgnetto psample hid_2013 bdpop /// 
using "${MY_PATH_IN}ppfad.dta", clear


* * * BALANCED VS UNBALANCED * * *

keep if ( (bfnetto >= 10 & bfnetto < 20) & (banetto >= 10 & banetto < 20) & (bgnetto >= 10 & bgnetto < 20) & (benetto >= 10 & benetto < 20) & (bbnetto >= 10 & bbnetto < 20) & (bdnetto >= 10 & bdnetto < 20) & (bcnetto >= 10 & bcnetto < 20) )


* * * ONLY PRIVATE HOUSEHOLDS * * *

keep if ( (bfpop == 1 | bfpop == 2) | (bapop == 1 | bapop == 2) | (bgpop == 1 | bgpop == 2) | (bepop == 1 | bepop == 2) | (bbpop == 1 | bbpop == 2) | (bdpop == 1 | bdpop == 2) | (bcpop == 1 | bcpop == 2) )


* * * GENDER ( male = 1 / female = 2) * * *

/* all genders */


* * * SAVE PFAD * * *

save "${MY_PATH_OUT}pfad.dta", replace 
clear


* * * HRF * * *

use bcphrf bfphrf bephrf baphrf prgroup bbphrf bdphrf cid bgphrf pid /// 
using "${MY_PATH_IN}phrf.dta" 
save "${MY_PATH_OUT}hrf.dta", replace 
clear


* * * CREATE MASTER * * *

use "${MY_PATH_OUT}pfad.dta", clear
merge 1:1 pid cid using "${MY_PATH_OUT}hrf.dta", keep(master match) nogen
save "${MY_PATH_OUT}master.dta", replace


* * * READ DATA * * *

use ijob110 e1110510 e1110110 ijob210 pid using "${MY_PATH_IN}bapequiv.dta", clear
save "${MY_PATH_OUT}bapequiv.dta", replace


use ijob113 ijob213 e1110513 e1110113 pid using "${MY_PATH_IN}bdpequiv.dta", clear
save "${MY_PATH_OUT}bdpequiv.dta", replace


use jobch10 emplst10 pid using "${MY_PATH_IN}bapgen.dta", clear
save "${MY_PATH_OUT}bapgen.dta", replace


use jobch13 emplst13 pid using "${MY_PATH_IN}bdpgen.dta", clear
save "${MY_PATH_OUT}bdpgen.dta", replace


use emplst16 jobch16 pid using "${MY_PATH_IN}bgpgen.dta", clear
save "${MY_PATH_OUT}bgpgen.dta", replace


use e1110514 ijob114 ijob214 e1110114 pid using "${MY_PATH_IN}bepequiv.dta", clear
save "${MY_PATH_OUT}bepequiv.dta", replace


use e1110116 ijob116 ijob216 e1110516 pid using "${MY_PATH_IN}bgpequiv.dta", clear
save "${MY_PATH_OUT}bgpequiv.dta", replace


use emplst15 jobch15 pid using "${MY_PATH_IN}bfpgen.dta", clear
save "${MY_PATH_OUT}bfpgen.dta", replace


use ijob112 ijob212 e1110112 e1110512 pid using "${MY_PATH_IN}bcpequiv.dta", clear
save "${MY_PATH_OUT}bcpequiv.dta", replace


use emplst12 jobch12 pid using "${MY_PATH_IN}bcpgen.dta", clear
save "${MY_PATH_OUT}bcpgen.dta", replace


use e1110115 ijob215 e1110515 ijob115 pid using "${MY_PATH_IN}bfpequiv.dta", clear
save "${MY_PATH_OUT}bfpequiv.dta", replace


use jobch11 emplst11 pid using "${MY_PATH_IN}bbpgen.dta", clear
save "${MY_PATH_OUT}bbpgen.dta", replace


use emplst14 jobch14 pid using "${MY_PATH_IN}bepgen.dta", clear
save "${MY_PATH_OUT}bepgen.dta", replace


use e1110511 ijob111 e1110111 ijob211 pid using "${MY_PATH_IN}bbpequiv.dta", clear
save "${MY_PATH_OUT}bbpequiv.dta", replace


* * * MERGE DATA * * *

use   "${MY_PATH_OUT}master.dta", clear
merge 1:1 pid using "${MY_PATH_OUT}bapequiv.dta", keep(master match) nogen
merge 1:1 pid using "${MY_PATH_OUT}bdpequiv.dta", keep(master match) nogen
merge 1:1 pid using "${MY_PATH_OUT}bapgen.dta", keep(master match) nogen
merge 1:1 pid using "${MY_PATH_OUT}bdpgen.dta", keep(master match) nogen
merge 1:1 pid using "${MY_PATH_OUT}bgpgen.dta", keep(master match) nogen
merge 1:1 pid using "${MY_PATH_OUT}bepequiv.dta", keep(master match) nogen
merge 1:1 pid using "${MY_PATH_OUT}bgpequiv.dta", keep(master match) nogen
merge 1:1 pid using "${MY_PATH_OUT}bfpgen.dta", keep(master match) nogen
merge 1:1 pid using "${MY_PATH_OUT}bcpequiv.dta", keep(master match) nogen
merge 1:1 pid using "${MY_PATH_OUT}bcpgen.dta", keep(master match) nogen
merge 1:1 pid using "${MY_PATH_OUT}bfpequiv.dta", keep(master match) nogen
merge 1:1 pid using "${MY_PATH_OUT}bbpgen.dta", keep(master match) nogen
merge 1:1 pid using "${MY_PATH_OUT}bepgen.dta", keep(master match) nogen
merge 1:1 pid using "${MY_PATH_OUT}bbpequiv.dta", keep(master match) nogen


* * * DONE * * *

label data "paneldata.org"
save "${MY_FILE_OUT}", replace
desc

log close